# Generated by Django 5.0.6 on 2024-07-11 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0005_alter_vetdoctor_appointment_fee_and_more'),
        ('users', '0007_pet_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('on_progress', 'On Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.consultationpackage')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.vetdoctor')),
            ],
        ),
    ]
