# Generated by Django 5.0.6 on 2024-07-09 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_doctor_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VetDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vet_doctor_pictures/')),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('specialties', models.ManyToManyField(to='consultations.speciality')),
            ],
        ),
        migrations.AlterField(
            model_name='consultationpackage',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='consultations.vetdoctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
