# Generated by Django 5.0.6 on 2024-07-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rename_consultation_fee_vetdoctor_appointment_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetdoctor',
            name='appointment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vetdoctor',
            name='chat_consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vetdoctor',
            name='voice_call_consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
