# Generated by Django 5.0.6 on 2024-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_vetdoctor_appointment_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationpackage',
            name='mode',
            field=models.CharField(choices=[('msg', 'Chat'), ('voice', 'Video Call'), ('video', 'Clinic Appointment')], max_length=5),
        ),
    ]
